apiVersion: v1
kind: Service
metadata:
  name: cloudcost-frontend-service
spec:
  selector:
    app: cloudcost-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
